app = "meu-jogo"
kill_signal = "SIGINT"
kill_timeout = 5


[build]
image = "node:20-alpine"


[env]
PORT = "8080"


[experimental]
allowed_public_ports = [3000]


[[services]]
internal_port = 3000
protocol = "tcp"
[services.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20
[[services.ports]]
handlers = ["http"]
port = 8080